;	db EVOLVE_ITEM, THUNDERSTONE, RAICHU
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, FLASH
	db 1, SAND_ATTACK
	db 6, SPARK
	db 8, TRI_ATTACK
	db 12, SCREECH
	db 18, THUNDER_WAVE
	db 21, THUNDERBOLT
	db 24, LIGHT_SCREEN
	db 28, SWIFT
	db 32, EARTHQUAKE
	db 38, THUNDER
	db 42, EXPLOSION
	db 50, MAGNITUDE
	db 61, ZAP_CANNON

	db 0 ; no more level-up moves