;	db EVOLVE_ITEM, THUNDERSTONE, RAICHU
	db 0 ; no more evolutions
	db 1, FAIRY_WIND
	db 1, MEAN_LOOK
	db 1, CALM_MIND
	db 8, CONFUSE_RAY
	db 14, CONFUSION
	db 16, WRAP
	db 20, NIGHT_SHADE
	db 26, DISABLE
	db 28, ACID
	db 30, FLAMETHROWER
	db 32, MOON_BLAST
	db 36, SHADOW_BALL
	db 38, PAIN_SPLIT
	db 42, DREAM_EATER
	db 50, MEGA_DRAIN
	db 0 ; no more level-up moves